name: My first workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Welcome message 
              run: 

            - name: Checkout repo
              uses: actions/checkout@v4

            - name: list and read files
              run: | 
                echo "My first GitHub Actions Job"
                ls -a
                cat README.md